libraryApp/urls.py
from django.contrib import admin
from django.urls import path, re_path

from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import thesisDetailView, ThesisCreate, ThesisUpdate, AdminThesisCreate, AdminThesisUpdate

from register import views as v

urlpatterns = [
    path('', views.index, name='home'),
    path('activate/<uidb64>/<token>/',v.activate, name='activate'),
    path('password_reset', v.password_reset_request, name="password_reset"),

    #Admin URLS
    path('admin/manageApproved/', views.manage_approved, name='manageApproved'),

    path('admin/uploadProject', AdminThesisCreate.as_view(), name='add'),
    path('admin/updateProject/<slug:slug>', AdminThesisUpdate.as_view(), name='edit_thesis'),
    path('admin/viewApproved/<slug:slug>', views.view_thesis, name='view_thesis'),

    path('admin/appprovedprojects_csv/', views.approvedprojects_csv, name='approvedcsv'),
    path('admin/viewRejected/<slug:slug>', views.view_thesisreject, name='view_thesisreject'),

    path('admin/managePending/', views.manage_pending, name='managePending'),
    path('admin/evaluate/<slug:slug>', views.evaluate, name='evaluate'),

    path('admin/manageRejected/', views.manage_rejected, name='manageRejected'),

    path('admin/dashboard/', views.dashboard, name='dashboard'),

    path('admin/manageRequests/', views.manage_request, name='manageRequests'),
    path('admin/evaluateRequests/<request_id>', views.evaluate_request, name='evaluateRequests'),

    path('admin/registeredaccounts_csv/', views.regaccs_csv, name='regaccscsv'),
    path('admin/registeredAccounts/', views.regAccounts, name='regAccounts'),
    path('admin/accountDetails/<user_id>', views.acc_details, name='acc_details'),

    path('admin/manageDepartment/', views.manage_dept, name='manage_dept'),
    path('admin/manageCourse/', views.manage_course, name='manage_course'),
    path('admin/editDepartment/<slug:slug>', views.edit_dept, name='edit_dept'),
    path('admin/deleteDepartment/<slug:slug>', views.delete_dept, name='delete_dept'),
    path('admin/editCourse/<slug:slug>', views.edit_course, name='edit_course'),
    path('admin/deleteCourse/<slug:slug>', views.delete_course, name='delete_course'),

    path('admin/disable_account/<user_id>', views.disable_account, name='disable_account'),
    path('admin/reactivate_account/<user_id>', views.reactivate_account, name='reactivate_account'),
    
    path('profile_staff/', views.profile_staff, name='profile_staff'),

    #User URLS
    path('repository/', views.thesis, name='thesis'),
    path('repository/view/<slug:slug>/', thesisDetailView.as_view(), name='view_studthesis'),
    #path('repository/view/<project_id>', views.view_studthesiss, name='view_studthesis'),
    path('repository/tag/<slug:slug>/', views.tagged, name="tagged"),
    path('repository/course/<slug:slug>', views.course_sort, name='course_sort'),

    path('submit/', ThesisCreate.as_view(), name='submission'),
    path('resubmit/<slug:slug>', ThesisUpdate.as_view(), name='resubmit'),

    path('viewPDF/<slug:slug>', views.viewPDF, name='viewPDF'),
    path('profile/', views.profile, name='profile'),
    path('personal_repository/', views.personal_repo, name='personal_repo'),
    path('myrepo_pdfviewer/<slug:slug>', views.myrepo_pdfviewer, name='myrepo_pdfviewer'),
    path('personal_access/', views.personal_access, name='personal_access'),
    path('delete_thesis/<slug:slug>', views.delete_thesis, name='delete_thesis'),

    re_path(r'^media/(?P<path>.*)$', views.protected_serve, {'document_root': settings.MEDIA_ROOT}),

    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

myProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from register import views as v
from libraryApp import views
#from allauth.account import views as allauth_views

urlpatterns = [
    path('', include('libraryApp.urls')),
    path('admin/', admin.site.urls),
    path('register/', v.register, name='register'),
    path('register_admin/', v.registerStaff, name='registerStaff'),
    path('accounts/login/', views.auth_login, name='login'),

    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    
    
    path('accounts/password_change/', views.password_change, name='password_change'),

    path('accounts/', include('django.contrib.auth.urls')),


    #path('accounts/', include('allauth.urls')),
]

handler404 = 'libraryApp.views.page_not_found'

libraryApp/models.py
from django.db import models
from django.db.models import Model
from django.db.models.functions import Lower

from taggit.managers import TaggableManager

from ckeditor.fields import RichTextField

from django.core.validators import RegexValidator

from django.contrib.auth.models import AbstractUser, User
from django.conf import settings

from django.core.validators import FileExtensionValidator, MinLengthValidator
from django.core.exceptions import ValidationError

from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation

import string 
from django.utils.text import slugify 
from .utils import unique_slugify

from django.utils import timezone
from datetime import date

# Create your models here.
#py manage.py makemigrations
#py manage.py migrate

class ColDept(Model):
	department_name = models.CharField(max_length=200, blank=True, null=True, verbose_name='Department', unique=True)
	department_abbreviation = models.CharField(max_length=200, blank=True, null=True, unique=True)
	slug = models.SlugField(max_length = 250, null = True, blank = True) 

	def save(self, *args, **kwargs):
		self.slug = slugify(self.department_name)
		super().save(*args, **kwargs)

	class Meta:
		db_table = 'col_dept'

	def __str__(self):
		department = str(self.department_name + " (" +self.department_abbreviation + ")")
		return department


class ColCourse(Model):
	course_name = models.CharField(max_length=200, blank=True, null=True, verbose_name='Course', unique=True)
	coldep_id = models.ForeignKey(ColDept, on_delete=models.CASCADE)
	slug = models.SlugField(max_length = 250, null = True, blank = True) 

	def save(self, *args, **kwargs):
		self.slug = slugify(self.course_name)
		super().save(*args, **kwargs)

	class Meta:
		db_table = 'col_course'

	def __str__(self):
		return self.course_name


def validate_file_size(value):
    filesize= value.size
    print('hello, i reached here')
    
    if filesize > 31457280:
        raise ValidationError("You cannot upload file more than 30Mb")
        print('hello')
    else:
    	print(value, filesize)
    	return value


THESIS_DECISION = (
	('Approved', 'Approve'),
	('Rejected', 'Reject')
	)


#my_validator = RegexValidator(r"'^[A-Z]\w+,\s*[A-Z]\.(?:\s+and (?:[A-Z]\w+,\s*[A-Z]\.|et\.\s+al\.))?'gm", "Invalid Format")
MONTH_CHOICES = (
	('1', 'January'),
	('2', 'February'),
	('3', 'March'),
	('4', 'April'),
	('5', 'May'),
	('6', 'June'),
	('7', 'July'),
	('8', 'August'),
	('9', 'September'),
	('10', 'October'),
	('11', 'November'),
	('12', 'December'),
	)

YEAR_CHOICES = [(y,y) for y in range(1968, date.today().year+1)]

class thesisDB(Model):
	thesis_id = models.AutoField(primary_key=True, blank=True, null=False)
	title = models.CharField(max_length=200, blank=True, null=True, unique=True)
	adviser = models.CharField(max_length=200, blank=True, null=True)
	published_year = models.IntegerField(choices=YEAR_CHOICES, default=date.today().year)
	published_month = models.CharField(max_length=15, choices=MONTH_CHOICES, default='1')
	pdf = models.FileField(upload_to='pdf/', blank=True, null=True ,validators=[FileExtensionValidator(['pdf']), validate_file_size],)
	course = models.ForeignKey(ColCourse, default=None, on_delete=models.CASCADE, verbose_name='Course')
	tags = TaggableManager()
	date_created = models.DateField(auto_now_add=True, blank=True, null=True )
	uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
	published_status = models.CharField(max_length=10, choices= THESIS_DECISION, default='Pending')
	abstract = models.TextField(blank=True, null=True, validators=[MinLengthValidator(50, 'the field must be at least 50 characters')])
	hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
	reason = models.TextField(blank=True, null=True)
	previous_reason = models.TextField(blank=True, null=True)
	slug = models.SlugField(max_length = 250, null = True, blank = True)
	apa = models.CharField(max_length=300, null=True, blank=True)
	mla = models.CharField(max_length=300, null=True, blank=True)
	chicago = models.CharField(max_length=300, null=True, blank=True)
	submission_agreement = models.BooleanField(default=False)

	def save(self, *args, **kwargs):
		#self.title = self.title.title()
		#self.author = self.author.title()
		self.slug = slugify(self.title + str(self.published_year))
		super().save(*args, **kwargs)
		
	class Meta:
		db_table = 'thesis_storage'
		

REQUEST_DECISION = (
	('Approved', 'Approve'),
	('Declined', 'Decline')
	)

class RequestPDF(Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	thesis = models.ForeignKey(thesisDB, on_delete=models.CASCADE)
	request_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	date_evaluated = models.DateTimeField(blank=True, null=True)
	request_status = models.CharField(max_length=10, choices=REQUEST_DECISION, default='Pending')
	reason = models.TextField(blank=True, null=True)
	slug = models.SlugField(max_length = 250, null = True, blank = True) 


class Registrations(AbstractUser):
	email = models.EmailField(unique=True)
	is_student = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)
	is_verified = models.BooleanField(default=False)

	def __str__(self):
		return self.first_name +" "+ self.last_name


class Authors(Model):
	thesis = models.ForeignKey(thesisDB, on_delete=models.CASCADE, related_name='thesis')
	first_name = models.CharField(max_length=200, blank=True, null=True)
	last_name = models.CharField(max_length=200, blank=True, null=True)

	def save(self, *args, **kwargs):
		self.first_name = self.first_name.title()
		self.last_name = self.last_name.title()
		super().save(*args, **kwargs)

libraryApp/templates/AdminEditCourse.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/Admin/Form.css' %}?{% now "U" %}"">

{% include 'Navibar.html' %}

<div class="container-fluid">
    <div class="row subcontainer">
        <div class="col-lg-2"></div>
        <div class="col-lg-8 bodycontent">
            <h4 class="textmaroon">Edit Course</h4>
            <p>Edit course here.</p>
            <hr></hr>
            <form class="form-group post-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                  <div class="col-md-12">
                    {{form | crispy}}
                  </div>
                </div>

                <div class="row">
                  <div class="col  mt-3 mb-3 ">
                    <button type="submit" class="btn btn-danger float-end">Update</button>
                    <button type="reset" class="btn btn-secondary me-2 float-end">Reset</button>
                    <a href="{% url 'manage_course' %}" class="btn btn-secondary">
                      Cancel
                    </a>
                  </div>
                </div>
             </form>
        </div>
    </div>
</div>


{% endblock %}

libraryApp/templates/AdminManageCourse.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/Admin/Deptform.css' %}?{% now "U" %}"">

{% include 'Navibar.html' %}

<div class="container-fluid coursecontainer">
    <div class="row coursecontent">
      <div class="col-lg-12">
          <div class="card cardheader p-3">
            <div class="row welcomebanner">
              <div class="col-lg-9 welcometext">
                  <h4>Program Management</h4>
                  <p>This is the management for programs in the system
                  </p>
              </div>
              <div class="col-lg-3">
                <img class="img-fluid" src="{% static 'Images/Dashboard.svg' %}" alt='dashboard'>
              </div>
            </div>
          </div>
      </div>
      <div class="col-lg-12 mt-5">
          <h4 class="textmaroon">Program Registration</h4>
          <p>Register a program here under a particular registered department.</p>
          <hr></hr>
          <form method="post" class="courseform" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-12">
                  {{form| crispy}}
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <button type="submit" class="btn float-end btn-danger mt-3">Register</button>
                  <button type="reset" class="btn float-end btn-secondary m-1 mt-3">Reset</button>
                </div>
              </div>
          </form>
      </div>
        
      <div class="col-lg-12 mt-5">
          <h4 class="textmaroon">Registered Programs</h4>
          <p>Here shows the registered programs in the system.</p>
          <hr></hr>
          <table id="book_table" class="table table-hover table-bordered"  style="width: 100%;">
            <thead>
              <tr>
                <th class="author" scope="col">Department</th>
                <th class="author" scope="col">Program Name</th>
                <th class="author" scope="col">Action</th>
              </tr>           
            </thead>

            <tbody>

              {% for co in course %}
              <tr>
                  <td>{{co.coldep_id}}</td>
                  <td>{{co.course_name}}</td>
                  <td>
                    <a href="{% url 'edit_course' co.slug %}" class="text-decoration-none text-decoration-none btn btn-primary">Edit</a>
                    <a href="{% url 'delete_course' co.slug %}" class="text-decoration-none btn btn-danger">Delete</a>
                </td>

              </tr>
              {% endfor %}        

            </tbody>
          </table>
      </div>

    </div>
</div>

{% block scripts %}

<script type="text/javascript">
$(document).ready(function() {
    $('#book_table').dataTable();
} );

</script>

{% endblock scripts %}

{% endblock %}

libraryApp/templates/AdminManageDepartment.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/Admin/Deptform.css' %}?{% now "U" %}"">

{% include 'Navibar.html' %}

<div class="container-fluid coursecontainer">
    <div class="row coursecontent">
        <div class="col-lg-12">
            <div class="card cardheader p-3">
              <div class="row welcomebanner">
                <div class="col-lg-9 welcometext">
                    <h4>Department Management</h4>
                    <p>This is the management for departments in the system
                    </p>
                </div>
                <div class="col-lg-3">
                  <img class="img-fluid" src="{% static 'Images/Dashboard.svg' %}" alt='dashboard'>
                </div>
              </div>
            </div>
        </div>

        <div class="col-lg-12 mt-5">
            <h4 class="textmaroon">Department Registrations</h4>
            <p>Try to register a department here</p>
            <hr></hr>
            <form method="post" class="courseform" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                  <div class="col-md-12">
                    {{form| crispy}}
                  </div>
                </div>

            <div class="row">
              <div class="col">
                <button type="reset" class="btn float-end btn-secondary m-1 mt-2 mb-2">Reset</button>
                <button type="submit" class="btn float-end btn-danger mt-2 mb-2">Register</button>
              </div>
            </div>
            </form>
        </div>
        
        <div class="col-lg-12 mt-5">
            <h4 class="textmaroon">Registered Courses</h4>
            <p>Here shows the registered courses in the system</p>
            <hr></hr>
            <table id="book_table" class="table table-hover table-bordered"  style="width: 100%;">
              <thead>
                <tr>
                  <th class="author" scope="col">Department</th>
                  <th class="author" scope="col">Department Abbrv.</th>
                  <th class="author" scope="col">Action</th>
                </tr>           
              </thead>

              <tbody>

                {% for dept in department %}
                <tr>
                    <td>{{dept.department_name}}</td>
                    <td>{{dept.department_abbreviation}}</td>
                    <td>
                      <a href="{% url 'edit_dept' dept.slug %}" class="text-decoration-none btn btn-primary">Edit</a>
                      <a href="{% url 'delete_dept' dept.slug %}" class="text-decoration-none btn btn-danger">Delete</a>
                  </td>

                </tr>
                {% endfor %}        

              </tbody>
            </table>
        </div>
    </div>
</div>

{% block scripts %}

<script type="text/javascript">
$(document).ready(function() {
    $('#book_table').dataTable();
} );

</script>

{% endblock scripts %}

{% endblock %}

libraryApp/templates/EvaluateRequests.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load hitcount_tags %}
{% load static %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/Admin/Evaluate.css' %}?{% now "U" %}"">

{% include 'Navibar.html' %}

<div class="container-fluid evaluatecontainer">
  <div class="evalbodycontainer">
      <div class="card cardheader p-3">
        <div class="row welcomebanner">
          <div class="col-lg-9 welcometext">
              <h4>Evaluate PDF Access Request</h4>
              <p>Evaluate requested access for PDF here
              </p>
          </div>
          <div class="col-lg-3">
            <img class="img-fluid" src="{% static 'Images/Dashboard.svg' %}" alt='dashboard'>
          </div>
        </div>
      </div>

      <div class="mt-5 row">
        <div class="col-lg-12 mb-3">
          <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger">
            <i class="bi bi-arrow-left-circle pe-1"></i>Back to previous page
          </a>
        </div>
        <div class="col-lg-6">
          <div class="card p-4">
            <div class="content">
              <h4 class="textmaroon mb-2">Requestor's Information</h4>
              <p class="m-0"><i class="bi bi-person-circle pe-1"></i>Name: 
                {{details.user.first_name}} {{details.user.last_name}}
              </p>
              <p class="m-0"><i class="bi bi-envelope pe-1"></i>Email: 
                <a href="mailto:{{detail.user.email}}">{{details.user.email}}</a>
              </p>
              <p class="m-0"><i class="bi bi-calendar pe-1"></i>Date Requested: 
                {{details.request_date}}
              </p>
              <p class="m-0"><i class="bi bi-chat-square pe-1"></i>Student's Reason: {{details.reason}}</p>
              <a href="{% url 'acc_details' details.user.id %}" class="btn btn-danger mt-3">View more &raquo;</a>
            </div>
          </div>
        </div>

        <div class="col-lg-6">
          <ul class="list-group list-group-flush card p-3">
              <li class="list-group-item m-0">
                  <div>
                      <h4><a class="text-decoration-none textmaroon" href="{% url 'view_thesis' details.thesis.slug %}" target="_blank">{{details.thesis.title}}
                      </a></h4>
                  </div>
                  <div class="content">
                      <p class="m-0"><i class="bi bi-person pe-1"></i>Author: 
                        {% for author in details.thesis.thesis.all %}
                        <span class="me-1 text-underline-decoration">{{author.first_name}} {{author.last_name}}</span>
                        {% endfor %}
                      </p>
                      <p class="m-0"><i class="bi bi-person pe-1"></i>Adviser: 
                        {{details.thesis.adviser}}
                      </p>
                      <p class="m-0"><i class="bi bi-building pe-1"></i>Course: {{details.thesis.course}}</p>
                      <p class="m-0"><i class="bi bi-calendar pe-1"></i>Published Date: {{details.thesis.get_published_month_display}} {{details.thesis.published_year}}</p>
                      <p class="m-0"><i class="bi bi-eye pe-1"></i>Views: {% get_hit_count for details.thesis %}</p>
                      <p class="m-0"><i class="bi bi-file-pdf pe-1"></i>PDF File: 
                          <a href="{{details.thesis.pdf.url}}" class="text-decoration-none" target="_blank">
                          View PDF
                          </a>
                      </p>
                      <p class="m-0"><i class="bi bi-calendar pe-1"></i>Submitted Date: {{details.thesis.date_created}}</p>
                      <p class="m-0"><i class="bi bi-person pe-1"></i>Submitted by:
                        {{details.thesis.uploaded_by}}
                      </p>
                      <div class="tags m-0">
                          <i class="bi bi-tags pe-1"></i>Keywords:
                          {% for tag in details.thesis.tags.all %}
                              <a class="textmaroon">{{tag}}
                              </a>
                          {% endfor %}
                      </div>
                  </div>
              </li>
          </ul>
          <div class="mt-3">
              {% include 'Admin/accordionabstract_v2.html' %}
          </div>
        </div>

      </div>

      <div class="mt-5 card p-4">
        <h4 class="textmaroon">Evaluate</h4>
        <form method="POST" class="form-group">
          {% csrf_token %}
          {{form|crispy}}
          <button type="submit" class="btn btn-danger mt-3 float-end">Confirm</button>
          <button type="submit" class="btn btn-secondary me-2 mt-3 float-end">Reset</button>
        </form>
      </div>
  </div>
</div>
{% endblock %}

libraryApp/templates/Footer.html
{% load static %}
{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/footer.css' %}?{% now "U" %}"">


<div class="container-fluid footer">
  <div class="row footerbody">
    <div class="col about">
      <h5>About</h5>
      <p>A Thesis Archive Management System for Technological University of The Philippines- Cavite for the digital preservation and management of thesis documents of the university.</p>
    </div>
    <div class="col contacts">
      <h5>Get in Touch</h5>
      <p>C.Q.T. Avenue Salawag, Dasmarinas City, Cavite</p>
      <p>+639471054225</p>
      <p>repository0612@gmail.com</p>
      <p>Mon - Fri, 8AM - 7PM</p>
    </div>
    <div class="col navlink">
      <h5 class="">Quick Links</h5>
      {% if user.is_authenticated and user.is_student %}
        <p><a href="{% url 'home' %}">Home</a></p>
        <p><a href="{% url 'profile' %}">Account</a></p>
        <p><a href="{% url 'logout' %}">Logout</a></p>
      {% else %}
        <p><a href="{% url 'login' %}">Login</a></p>
        <p><a href="{% url 'register' %}">Signup</a></p>
      {% endif %}
    </div>
  </div>
  <div class="row footerbottom">
    <hr>
    <p>All rights reserved @ 2023</p>
  </div>
</div>





{% endblock content %}

libraryApp/templates/PendingRequestPDF.html
{% extends 'main.html' %}
{% load static %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/PDFRequest/requestpdf.css' %}?{% now "U" %}"">

{% include 'Navibar.html' %}

<div class="container-fluid requestcontainer">
	<div class="row">
		<div class="col-lg-2"></div>
		<div class="col-lg-8 requestcontent">
			<h4 class="text-maroon">Your request is PENDING</h4>
			<p>Your request to access the document file of the thesis project entitled
				<span class="thesistitle">"{{detail.title}}"</span>
			has successfully been sent and is currently pending. In the meantime, we ask you to wait until the confirmation of your request.</p>
		</div>
		<div class="col-lg-2"></div>
	</div>
</div>

{% include 'Footer.html' %}

{% endblock %}

libraryApp/templates/ThesisDetails.html
{% extends 'main.html' %}
{% load static %}
{% load hitcount_tags %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/MainRepository/thesisdetails.css' %}?{% now "U" %}"">

{% include 'Navibar.html' %}

<div class="container-fluid content">
	<div class="row mainbody">
		<div class="col-lg-12 thesisdetail">
			<div class="mb-3">
				<a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger">
					<i class="bi bi-arrow-left-circle pe-1"></i>Back to previous page
				</a>
			</div>
			<div>
				<h5>{{detail.title}}</h5>
			</div>

			<div class="details">
				<p class="m-0"><i class="bi bi-person pe-1"></i>By
                    {% for author in authors %}     
                    <span class="me-1 text-decoration-underline">{{author.first_name}} {{author.middle_initial}} {{author.last_name}}</span>
                    {% endfor %}
                </p>
                <p class="m-0"><i class="bi bi-person-fill pe-1"></i>Thesis Advisor
                    {{detail.adviser}}
                </p>
				<p class="m-0"><i class="bi bi-building pe-1"></i>{{detail.course}}</p>
				<p class="m-0"><i class="bi bi-calendar pe-1"></i>Published in  {{detail.get_published_month_display}} {{detail.published_year}}</p>
				<p class="m-0"><i class="bi bi-eye pe-1"></i>{% get_hit_count for detail %} views</p>
				<div class="tags m-0">
				    <i class="bi bi-tags pe-1"></i>
				    {% for tag in detail.tags.all %}
				        <a href="{% url 'tagged' tag.slug %}" class="textmaroon text-decoration-none">{{tag}}</a>
				    {% endfor %}
				</div>
				<p><i class="bi bi-file-pdf pe-1"></i>
					<a href="{% url 'viewPDF' detail.slug %}" class="text-decoration-none" target="blank_">
						View PDF File
					</a>
				</p>
			</div>

			<div class="abstract mb-3">
				{% include "MainRepository/abstract.html"%}
			</div>

			<div class="mb-3">
				<h5 class="textmaroon">Recommended Citation</h5>
				{% include "MainRepository/citationcanvas.html"%}
			</div>
		</div>
	</div>
</div>

{% include 'Footer.html' %}

{% block scripts %}
<script>
	function CopyToClipboard(id)
	  {
	    var r = document.createRange();
	    r.selectNode(document.getElementById(id));
	    window.getSelection().removeAllRanges();
	    window.getSelection().addRange(r);
	    document.execCommand('copy');
	    window.getSelection().removeAllRanges();
	}
</script>
{% endblock scripts %}

{% endblock %}

libraryApp/templates/account_activation.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/Registrations/login.css' %}?{% now "U" %}"">

{% include 'Navibar.html' %}

<div class="container-fluid">
  <div class="row loginrow">
    <div class="col-lg-6 col-sm-12 left_section">
      <img class="img-fluid" src="{% static 'Images/Login.svg' %}" alt='password'>
    </div>
    <div class="col-lg-6 col-sm-12 right_section">
      <h4 class="textmaroon">Email Verification Has Been Sent<i class="bi bi-check-circle ps-1 fs-1"></i></h4>
      <p class="textcon">Please confirm your email address to complete the registration
      </p>
      <div class="d-flex align-items-center">
      	<a href="{% url 'home' %}" class="btn btn-danger">Okay &raquo;</a>
      </div>     
    </div>

  </div>
</div>

{% include 'Footer.html' %}
{% endblock%}